# -*- coding: utf-8 -*-
"""analise-raça-money.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gVM263I0-QKPFRqp2CaH8GmZviiZmMHt

## Fonte: https://sidra.ibge.gov.br/pesquisa/pnadcm/tabelas

# Nova seção
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pylab as pl
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from matplotlib.lines import Line2D
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

cargo_df = pd.read_excel("/content/Cargos_2018.xlsx")

display(cargo_df)

plt.figure(figsize=(13,8),dpi=90)
plt.title('Trabalhadores em cargos gerenciais - Pesquisa 2018');
plt.style.use('seaborn-darkgrid')
sns.barplot(data=cargo_df, x="Cor_pele", y="Porcentagem", capsize=100)
# Adicionando os valores nas barras
for index, row in cargo_df.iterrows():
    plt.text(row.name, row.Porcentagem, round(row.Porcentagem, 2), color='black', ha="center")
    
plt.xlabel('Fonte dos Dados: https://sidra.ibge.gov.br/pesquisa/pnadcm/tabelas');
plt.savefig("relatorio1.pdf", bbox_inches="tight")

"""
Tabela 2.5 - Rendimento médio real habitual do trabalho principal das pessoas de 14 anos ou mais de idade, ocupadas na semana de referência e em ocupações formais e informais, por cor ou raça, segundo as Grandes Regiões, as Unidades da Federação e os Municípios das Capitais - Brasil - 2021"""

renda_df = pd.read_excel("/content/redimentos_medio.xlsx")
renda_df['Redimento_medio'] = pd.to_numeric(renda_df['Redimento_medio'])

display(renda_df)



plt.figure(figsize=(13,8),dpi=90)
sns.set_style("darkgrid")
plt.title('Remuneração média em real - pesquisa ano 2021');
plt.style.use('seaborn-darkgrid')
sns.barplot(data=renda_df, x="cor_pele", y="Redimento_medio");

# Adicionando os valores nas barras
for index, row in renda_df.iterrows():
    plt.text(row.name, row.Redimento_medio, round(row.Redimento_medio, 2), color='black', ha="center")

plt.xlabel('Fonte dos Dados: https://sidra.ibge.gov.br/pesquisa/pnadcm/tabelas');



plt.savefig("relatorio2.pdf", bbox_inches="tight")

